#!/bin/bash

case $# in
    0) echo "Parameters not recognized, type compile --help for help";;
    1) FILE=$1;;
    *) echo "Parameters not recognized, type compile --help for help";;
esac

NAME=$(echo $FILE | cut -f1 -d '.')

if [ "$FILE" = "--help" ]
then
    echo "Usage- $ compile <filename with extension>"
    echo "Only for .c and .cpp files"

elif [ "${FILE##*.}" = "c" ]
then
    gcc -c $FILE -o temp.o
    gcc temp.o -o $NAME
    rm temp.o

elif [ "${FILE##*.}" = "cpp" ]
then
    g++ -c $FILE -o temp.o
    g++ temp.o -o $NAME
    rm temp.o

else
    echo "Invalid file extension"

fi
